<a href="https://colab.research.google.com/github/SachiSachu/1stop/blob/main/numpy1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
#import pandas as pd

In [4]:
dt = np.dtype(np.int32) #int8, int16, int32, int64 are equal to i1, i2, i3, i4
dt

dtype('int32')

In [7]:
#endian data types
dp = np.dtype([('age', np.int8)])
dp

dtype([('age', 'i1')])

In [10]:
#applying to ndarray
dat = np.array([10,20,30], dtype=dt)
dat

array([10, 20, 30], dtype=int32)

In [12]:
#2 dimensional array
#we have a nested list
a = [[1,2,3],[4,5,6],[7,8,9]] 
a

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [19]:
#now converting into 2d array
a = np.array(a)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
#writing above array as complex data types
np.array(a, dtype=complex)

array([[1.+0.j, 2.+0.j, 3.+0.j],
       [4.+0.j, 5.+0.j, 6.+0.j],
       [7.+0.j, 8.+0.j, 9.+0.j]])

In [20]:
#attributes
#to know the size of matrix we use shape
a.shape

(3, 3)

In [26]:
#reshaping it and should follow m x n = m' x n' == number of elements
b = np.array([[1,2,3],[3,4,1]])
print(b)
print(b.shape)
#converting it to 3,2 shape
b.shape=(3,2)
b

[[1 2 3]
 [3 4 1]]
(2, 3)


array([[1, 2],
       [3, 3],
       [4, 1]])

In [36]:
#to arrange elements
z = np.arange(24)
print(z.shape)#one dimensional array from 0 to 24
z.shape = (4,6)
print('***********************************')
print(z)
#gcd of fact of 24 are 2,3,4
y = np.arange(24)
y.shape = (2,3,4)
print('***********************************')
y

(24,)
***********************************
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
***********************************


array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [43]:
#numpy Math
import math as m
#floor value of 7.3
print(m.floor(7.3))

#square root
print(m.sqrt(3))

#ceil value 
print(m.ceil(7.3))

#trigonometric values
print(m.sin(3))

7
1.7320508075688772
8
0.1411200080598672


In [48]:
arr = np.array([1,2,3,4,5])
srt = arr + 5
srt

array([ 6,  7,  8,  9, 10])

numpy operations

In [51]:
a = np.array([1,2,3,4,5])
b = np.array([9,8,7,6,5])
print(a+5) # instead + you can use any operations
print(b+4)
a+b

[ 6  7  8  9 10]
[13 12 11 10  9]


array([10, 10, 10, 10, 10])

In [53]:
a.mean()

3.0

In [54]:
a.sum()

15